name: Deploy to Cloud Run

on:
  push:
<<<<<<< HEAD
    branches: [ main ]
=======
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
>>>>>>> 0bad84a9b3ff1c4d4a1dd47d9f5dc0bcd94a123b

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: zachat-465817

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker


      - name: Build Docker image
        run: docker build -t gcr.io/zachat-465817/zalo-backend:${{ github.sha }} .

      - name: Push Docker image
        run: docker push gcr.io/zachat-465817/zalo-backend:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy zalo-backend \
            --image gcr.io/zachat-465817/zalo-backend:${{ github.sha }} \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
