      - name: SSH and deploy to GCE
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: |
            export PATH=$PATH:/snap/bin
            if [ -d "/home/${{ secrets.GCE_USER }}/zalo-backend" ]; then
              cd /home/${{ secrets.GCE_USER }}/zalo-backend
              git reset --hard
              git clean -fd
              git pull origin main --rebase
            else
              git clone https://github.com/Thu-Hong-oo/zalo-backend.git /home/${{ secrets.GCE_USER }}/zalo-backend
              cd /home/${{ secrets.GCE_USER }}/zalo-backend
            fi

            echo "${{ secrets.ENV_FILE }}" > .env
            docker build -t zalo-backend .
            docker stop zalo-backend || true
            docker rm zalo-backend || true
            docker run -d \
              --name zalo-backend \
              --restart unless-stopped \
              --env-file .env \
              -p 3000:3000 \
              zalo-backend